name = "LoopRecipes"
uuid = "dfd03e4f-9f78-4c46-a6d7-9511b162999f"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
Transducers = "0.4"
julia = "1"
